BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (1, 1, 'Bulbasaur', 'grass', 'poison');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (2, 2, 'Ivysaur', 'grass', 'poison');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (3, 3, 'Venusaur', 'grass', 'poison');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (198, 198, 'Murkrow', 'dark', 'flying');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (285, 285, 'Shroomish', 'grass');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (286, 286, 'Breloom', 'grass', 'fighting');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (352, 352, 'Kecleon', 'normal');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (407, 407, 'Roserade', 'grass', 'poison');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (425, 425, 'Drifloon', 'ghost', 'flying');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (426, 426, 'Drifblim', 'ghost', 'flying');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (430, 430, 'Honchkrow', 'dark', 'flying');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (456, 456, 'Finneon', 'water');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (457, 457, 'Lumineon', 'water');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (556, 556, 'Maractus', 'grass');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (568, 568, 'Trubbish', 'poison');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (569, 569, 'Garbodor', 'poison');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (582, 582, 'Vanillite', 'ice');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (583, 583, 'Vanillish', 'ice');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (584, 584, 'Vanilluxe', 'ice');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (607, 607, 'Litwick', 'ghost', 'fire');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (608, 608, 'Lampent', 'ghost', 'fire');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (609, 608, 'Chandelure', 'ghost', 'fire');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (626, 626, 'Bouffalant', 'normal');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (636, 636, 'Larvesta', 'bug', 'fire');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (637, 637, 'Volcarona', 'bug', 'fire');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (661, 661, 'Fletchling', 'normal', 'flying');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (662, 662, 'Fletchinder', 'fire', 'flying');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (663, 663, 'Talonflame', 'fire', 'flying');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (684, 684, 'Swirlix', 'fairy');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (685, 685, 'Slurpuff', 'fairy');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (698, 698, 'Amaura', 'rock', 'ice');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (699, 699, 'Aurorus', 'rock', 'ice');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (701, 701, 'Hawlucha', 'fighting', 'flying');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (780, 780, 'Drampa', 'normal', 'dragon');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (840, 840, 'Applin', 'grass', 'dragon');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (841, 841, 'Flapple', 'grass', 'dragon');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (842, 842, 'Appletun', 'grass', 'dragon');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (848, 848, 'Toxel', 'electric', 'poison');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (849, 849, 'Toxtricity', 'electric', 'poison');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (866, 866, 'Mr. Rime', 'ice', 'psychic');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (874, 874, 'Stonjourner', 'rock');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (878, 878, 'Cufant', 'steel');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (879, 879, 'Copperajah', 'steel');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (902, 902, 'Basculegion', 'water', 'ghost');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (912, 912, 'Quaxly', 'water');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (913, 913, 'Quaxwell', 'water');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (914, 914, 'Quaquaval', 'water', 'fighting');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (935, 935, 'Charcadet', 'fire');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (936, 936, 'Armarouge', 'fire', 'psychic');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (937, 937, 'Ceruledge', 'fire', 'ghost');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (940, 940, 'Wattrel', 'electric', 'flying');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (941, 941, 'Kilowattrel', 'electric', 'flying');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (948, 948, 'Toedscool', 'ground', 'grass');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (949, 949, 'Toadscruel', 'ground', 'grass');
INSERT INTO pokemon(id, pokedex_number, name, type1) VALUES (950, 950, 'Klawf', 'rock');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (973, 973, 'Flamigo', 'flying', 'fighting');
INSERT INTO pokemon(id, pokedex_number, name, type1, type2) VALUES (980, 980, 'Clodsire', 'poison', 'ground');

COMMIT TRANSACTION;
